//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OICPen.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OICPen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap _0m012d825c5b12705c606812447e243c22686e64752f477d470e7f396f7a3237746837646131373e59 {
            get {
                object obj = ResourceManager.GetObject("0m012d825c5b12705c606812447e243c22686e64752f477d470e7f396f7a3237746837646131373e5" +
                        "9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap _30215yq {
            get {
                object obj = ResourceManager.GetObject("30215yq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap _4322 {
            get {
                object obj = ResourceManager.GetObject("4322", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap _57_512 {
            get {
                object obj = ResourceManager.GetObject("57-512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap _6909249_black_hd_background {
            get {
                object obj = ResourceManager.GetObject("6909249-black-hd-background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap _869c0d3a69611c1f4e976184393fc81c {
            get {
                object obj = ResourceManager.GetObject("869c0d3a69611c1f4e976184393fc81c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap _8bc8a23c65c1d8ced3aab5a7317fa5d4 {
            get {
                object obj = ResourceManager.GetObject("8bc8a23c65c1d8ced3aab5a7317fa5d4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap _8ccc758cae6b87ab33fdf23b2548bbfc {
            get {
                object obj = ResourceManager.GetObject("8ccc758cae6b87ab33fdf23b2548bbfc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap _8ccc758cae6b87ab33fdf23b2548bbfc1 {
            get {
                object obj = ResourceManager.GetObject("8ccc758cae6b87ab33fdf23b2548bbfc1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap alienware_ui___for_windows_7_by_mvgraphics {
            get {
                object obj = ResourceManager.GetObject("alienware_ui___for_windows_7_by_mvgraphics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap C4n3i10WQAEmisf {
            get {
                object obj = ResourceManager.GetObject("C4n3i10WQAEmisf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap colored_pencils9 {
            get {
                object obj = ResourceManager.GetObject("colored-pencils9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap colored_pencils91 {
            get {
                object obj = ResourceManager.GetObject("colored-pencils91", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cooltext302672380550070 {
            get {
                object obj = ResourceManager.GetObject("cooltext302672380550070", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cooltext3026723805500701 {
            get {
                object obj = ResourceManager.GetObject("cooltext3026723805500701", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cooltext302672489979675 {
            get {
                object obj = ResourceManager.GetObject("cooltext302672489979675", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cooltext302672549851951 {
            get {
                object obj = ResourceManager.GetObject("cooltext302672549851951", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cooltext302673263607342 {
            get {
                object obj = ResourceManager.GetObject("cooltext302673263607342", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cooltext302673350769687 {
            get {
                object obj = ResourceManager.GetObject("cooltext302673350769687", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cooltext302673427531843 {
            get {
                object obj = ResourceManager.GetObject("cooltext302673427531843", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cooltext302673740273912 {
            get {
                object obj = ResourceManager.GetObject("cooltext302673740273912", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cooltext3026737402739121 {
            get {
                object obj = ResourceManager.GetObject("cooltext3026737402739121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cooltext302673830226924 {
            get {
                object obj = ResourceManager.GetObject("cooltext302673830226924", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cooltext3026738302269241 {
            get {
                object obj = ResourceManager.GetObject("cooltext3026738302269241", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cooltext302673864705453 {
            get {
                object obj = ResourceManager.GetObject("cooltext302673864705453", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cooltext3026738647054531 {
            get {
                object obj = ResourceManager.GetObject("cooltext3026738647054531", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cooltext302673919131457 {
            get {
                object obj = ResourceManager.GetObject("cooltext302673919131457", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cooltext302674035806542 {
            get {
                object obj = ResourceManager.GetObject("cooltext302674035806542", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cooltext302674204837578 {
            get {
                object obj = ResourceManager.GetObject("cooltext302674204837578", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cooltext302674252430085 {
            get {
                object obj = ResourceManager.GetObject("cooltext302674252430085", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cooltext303079794295816 {
            get {
                object obj = ResourceManager.GetObject("cooltext303079794295816", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cooltext303079880444938 {
            get {
                object obj = ResourceManager.GetObject("cooltext303079880444938", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cooltext303079969969450 {
            get {
                object obj = ResourceManager.GetObject("cooltext303079969969450", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cooltext303080754992354 {
            get {
                object obj = ResourceManager.GetObject("cooltext303080754992354", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap f96bd45644a9657a147645c0f763f701 {
            get {
                object obj = ResourceManager.GetObject("f96bd45644a9657a147645c0f763f701", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap f96bd45644a9657a147645c0f763f7011 {
            get {
                object obj = ResourceManager.GetObject("f96bd45644a9657a147645c0f763f7011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap fc3ec593_dffc_411c_8717_21f97af10a68 {
            get {
                object obj = ResourceManager.GetObject("fc3ec593-dffc-411c-8717-21f97af10a68", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap fc3ec593_dffc_411c_8717_21f97af10a681 {
            get {
                object obj = ResourceManager.GetObject("fc3ec593-dffc-411c-8717-21f97af10a681", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap gahag_0055923193_1 {
            get {
                object obj = ResourceManager.GetObject("gahag-0055923193-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap hello_i_m_nik_745051_unsplash {
            get {
                object obj = ResourceManager.GetObject("hello-i-m-nik-745051-unsplash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_curved_arrow_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-curved-arrow-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_in_transit_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-in-transit-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_in_transit_482 {
            get {
                object obj = ResourceManager.GetObject("icons8-in-transit-482", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_left_2_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-left-2-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_left_2_481 {
            get {
                object obj = ResourceManager.GetObject("icons8-left-2-481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_return_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-return-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_sales_performance_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-sales-performance-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_ショッピングカート_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-ショッピングカート-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_ショッピングカート_641 {
            get {
                object obj = ResourceManager.GetObject("icons8-ショッピングカート-641", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_ユーザー_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-ユーザー-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_ユーザー_64__1_ {
            get {
                object obj = ResourceManager.GetObject("icons8-ユーザー-64 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_二重左矢印_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-二重左矢印-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_二重左矢印_48__1_ {
            get {
                object obj = ResourceManager.GetObject("icons8-二重左矢印-48 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_倉庫_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-倉庫-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_倉庫_64__2_ {
            get {
                object obj = ResourceManager.GetObject("icons8-倉庫-64 (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_出口_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-出口-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_出口_641 {
            get {
                object obj = ResourceManager.GetObject("icons8-出口-641", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_削除_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-削除-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_削除_641 {
            get {
                object obj = ResourceManager.GetObject("icons8-削除-641", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_日本円_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-日本円-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_日本円_641 {
            get {
                object obj = ResourceManager.GetObject("icons8-日本円-641", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_注文書_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-注文書-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_注文書_641 {
            get {
                object obj = ResourceManager.GetObject("icons8-注文書-641", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_社員カード_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-社員カード-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_社員カード_64__1_ {
            get {
                object obj = ResourceManager.GetObject("icons8-社員カード-64 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_製品_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-製品-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_製品_641 {
            get {
                object obj = ResourceManager.GetObject("icons8-製品-641", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_配達_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-配達-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_配達_641 {
            get {
                object obj = ResourceManager.GetObject("icons8-配達-641", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_配達_642 {
            get {
                object obj = ResourceManager.GetObject("icons8-配達-642", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap if_1_1668045 {
            get {
                object obj = ResourceManager.GetObject("if_1_1668045", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap img_depot {
            get {
                object obj = ResourceManager.GetObject("img_depot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap img_depot1 {
            get {
                object obj = ResourceManager.GetObject("img_depot1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap img_logo {
            get {
                object obj = ResourceManager.GetObject("img_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap img_logo_footer01 {
            get {
                object obj = ResourceManager.GetObject("img_logo_footer01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_colored_pencil_drawing_stationery_clip_art_cartoon_pencil_5a94bf66556055_9463497515196977663497 {
            get {
                object obj = ResourceManager.GetObject("kisspng-colored-pencil-drawing-stationery-clip-art-cartoon-pencil-5a94bf66556055." +
                        "9463497515196977663497", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_colored_pencil_drawing_stationery_clip_art_cartoon_pencil_5a94bf665560551 {
            get {
                object obj = ResourceManager.GetObject("kisspng-colored-pencil-drawing-stationery-clip-art-cartoon-pencil-5a94bf665560551" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_colored_pencil_drawing_stationery_clip_art_cartoon_pencil_5a94bf665560552 {
            get {
                object obj = ResourceManager.GetObject("kisspng-colored-pencil-drawing-stationery-clip-art-cartoon-pencil-5a94bf665560552" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_colored_pencil_drawing_stationery_clip_art_cartoon_pencil_5a94bf665560553 {
            get {
                object obj = ResourceManager.GetObject("kisspng-colored-pencil-drawing-stationery-clip-art-cartoon-pencil-5a94bf665560553" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_login_user_system_administrator_ima_editing_mafsyah_template_5b75843a7b1045_0356392015344282185041 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-login-user-system-administrator-ima-editing-mafsyah-templa" +
                        "te-5b75843a7b1045.0356392015344282185041", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_paper_stationery_adhesive_tape_ant_stationers_offi_school_png_image_5a752e58967e98_7882915715176290166164 {
            get {
                object obj = ResourceManager.GetObject("kisspng-paper-stationery-adhesive-tape-ant-stationers-offi-school-png-image-5a752" +
                        "e58967e98.7882915715176290166164", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_rectangle_horizontal_line_5ac44e44e7fce7_2607150015228145329502 {
            get {
                object obj = ResourceManager.GetObject("kisspng-rectangle-horizontal-line-5ac44e44e7fce7.2607150015228145329502", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Login_Screen_Background_Wood_5 {
            get {
                object obj = ResourceManager.GetObject("Login-Screen-Background-Wood-5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Login_Screen_Background_Wood_51 {
            get {
                object obj = ResourceManager.GetObject("Login-Screen-Background-Wood-51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap oiclogopng {
            get {
                object obj = ResourceManager.GetObject("oiclogopng", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap pencil_box_clipart_28 {
            get {
                object obj = ResourceManager.GetObject("pencil-box-clipart-28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap purepng_com_erasereraserstationeryremovingwritingrubberyshapescolourspencil_eraser_1421526504923jaacw {
            get {
                object obj = ResourceManager.GetObject("purepng.com-erasereraserstationeryremovingwritingrubberyshapescolourspencil-erase" +
                        "r-1421526504923jaacw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap school_stationery_items_1520937446_3716503 {
            get {
                object obj = ResourceManager.GetObject("school-stationery-items-1520937446-3716503", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap school_stationery_items_1520937446_37165031 {
            get {
                object obj = ResourceManager.GetObject("school-stationery-items-1520937446-37165031", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap set_of_stationery_pictures_csp39459981 {
            get {
                object obj = ResourceManager.GetObject("set-of-stationery-pictures_csp39459981", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap set_of_stationery_pictures_csp394599811 {
            get {
                object obj = ResourceManager.GetObject("set-of-stationery-pictures_csp394599811", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap splash {
            get {
                object obj = ResourceManager.GetObject("splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap stationary_500x500 {
            get {
                object obj = ResourceManager.GetObject("stationary-500x500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ダウンロード__1_ {
            get {
                object obj = ResourceManager.GetObject("ダウンロード (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ダウンロード__2_ {
            get {
                object obj = ResourceManager.GetObject("ダウンロード (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 蜃ｺ蠎ｫ {
            get {
                object obj = ResourceManager.GetObject("蜃ｺ蠎ｫ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
